### PR TITLE
fix segment fault when getting zero size user code packet in openzwav…

### PR DESCRIPTION
**Pull request by binli71**
The patch fixes segment fault when getting zero size user code packet in openzwave library.

### CODE REVIEW

**Comment by dhylands** [comment]
I'm also running into this issue, but the PR looks bad.

I'm happy to prepare a proper PR (that only affects the couple lines that are supposed to be changed).

**Comment by binli71** [comment]
Hello, Dave,

I am fine if you can prepare a proper PR.
I will be more happy to know what is the right process to follow for the 
future.
Do you mind give me a hand about how to prepare a proper PR?

I guess the right way should be as below.
- git clone <my forked master>
- create a branch
- commit the code under this branch
- put the fix to the new branch
- create Pull Request of this new branch instead of from master
- one fix per PR

Regards
Bin

**Comment by dhylands** [comment]
That sounds like the correct flow.
https://guides.github.com/introduction/flow/

Some other people have their own minor variants:
https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/Development-workflow-with-Git:-Fork,-Branching,-Commits,-and-Pull-Request

What's really key is that your commit should only have the changed lines in it and not anything else.

**Comment by binli71** [comment]
Thanks for the information.

I opened a new PR. Would you mind to have have look to see any thing 
still need to be changed?

https://github.com/OpenZWave/open-zwave/pull/858

Regards
Bin

**Comment by Fishwaldo** [comment]
Thanks

**Pull request merged**
